global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway-service:9000"]

  - job_name: query-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["query-service:8083"]

  - job_name: vector-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["vector-service:8084"]

  - job_name: ranking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ranking-service:8085"]

  - job_name: fusion-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["fusion-service:8087"]

  - job_name: caching-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["caching-service:8096"]

  - job_name: monitoring-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["monitoring-service:9090"]
