server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/metadata_db
    username: hybrid
    password: hybrid123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
