apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-pgvector
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-pgvector
          image: postgres:16
          env:
            - name: PGPASSWORD
              value: hybrid123
          volumeMounts:
            - name: schema-sql
              mountPath: /schema
          command:
            - /bin/sh
            - -c
            - |
              psql -h postgres -U hybrid -d metadata_db -f /schema/init-schema.sql
      volumes:
        - name: schema-sql
          configMap:
            name: postgres-schema-sql
